### ISSUE TITLE
300S Generating Unknown mode 'auto' warnings

### ISSUE THREAD

**Issue by RobertD502** [vlebourl/custom_vesync#142]
### The problem

300s Humidifier is generating countless warnings about unknown mode 'auto' as well as the auto mode missing in the Humidifier entity.

The warning is being raised by the [available modes](https://github.com/vlebourl/custom_vesync/blob/f6d69cc74cdf369b088ec56d347127b2a0279226/custom_components/vesync/humidifier.py#L106-L118), [mode](https://github.com/vlebourl/custom_vesync/blob/f6d69cc74cdf369b088ec56d347127b2a0279226/custom_components/vesync/humidifier.py#L130-L133), and [extra state attributes](https://github.com/vlebourl/custom_vesync/blob/f6d69cc74cdf369b088ec56d347127b2a0279226/custom_components/vesync/humidifier.py#L145-L157) properties.

Note: It seems the version key wasn't updated in the manifest for the beta, so, disregard the version discrepancy seen in the diagnostics. 

### What version of this integration has the issue?

1.0.0-beta1

### What version of Home Assistant Core has the issue?

2023.4.6

### Diagnostics

<details><summary>Diagnostics</summary>

```json
{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2023.4.6",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.10.10",
    "docker": true,
    "arch": "x86_64",
    "timezone": "America/New_York",
    "os_name": "Linux",
    "os_version": "6.1.24",
    "supervisor": "2023.04.1",
    "host_os": "Home Assistant OS 10.0",
    "docker_version": "23.0.3",
    "chassis": "vm",
    "run_as_root": true
  },
  "custom_components": {
  "integration_manifest": {
    "domain": "vesync",
    "name": "VeSync",
    "codeowners": [
      "@markperdue",
      "@webdjoe",
      "@thegardenmonkey",
      "@vlebourl"
    ],
    "config_flow": true,
    "dhcp": [
      {
        "hostname": "levoit-*",
        "macaddress": "*"
      }
    ],
    "documentation": "https://www.home-assistant.io/integrations/vesync",
    "iot_class": "cloud_polling",
    "issue_tracker": "https://github.com/vlebourl/custom_vesync",
    "requirements": [
      "pyvesync==2.1.6"
    ],
    "version": "0.2.5",
    "is_built_in": false
  },
  "data": {
    "humidifier": [
      {
        "device_name": "Bedroom Humidifier",
        "device_image": "https://image.vesync.com/defaultImages/deviceDefaultImages/wifibtonboardingnotify_airhumidifier_classic300s_us_240.png",
        "cid": "**REDACTED**",
        "connection_status": "online",
        "connection_type": "WiFi+BTOnboarding+BTNotify",
        "device_type": "Classic300S",
        "type": "wifi-air",
        "uuid": "**REDACTED**",
        "config_module": "WiFiBTOnboardingNotify_AirHumidifier_Classic300S_US",
        "mac_id": "**REDACTED**",
        "mode": null,
        "speed": null,
        "extension": null,
        "current_firm_version": null,
        "device_region": "US",
        "pid": null,
        "sub_device_no": null,
        "config": {
          "auto_target_humidity": 45,
          "display": false,
          "automatic_stop": true
        },
        "device_status": "off",
        "enabled": false,
        "config_dict": {
          "module": "VeSyncHumid200300S",
          "models": [
            "Classic300S",
            "LUH-A601S-WUSB"
          ],
          "features": [
            "nightlight"
          ],
          "mist_modes": [
            "auto",
            "sleep",
            "manual"
          ],
          "mist_levels": [
            1,
            2,
            3,
            4,
            5,
            6,
            7,
            8,
            9
          ]
        },
        "mist_levels": [
          1,
          2,
          3,
          4,
          5,
          6,
          7,
          8,
          9
        ],
        "mist_modes": [
          "auto",
          "sleep",
          "manual"
        ],
        "features": [
          "nightlight"
        ],
        "warm_mist_feature": false,
        "warm_mist_levels": [],
        "night_light": true,
        "details": {
          "humidity": 62,
          "mist_virtual_level": 1,
          "mist_level": 1,
          "mode": "auto",
          "water_lacks": false,
          "humidity_high": false,
          "water_tank_lifted": false,
          "display": false,
          "automatic_stop_reach_target": true,
          "night_light_brightness": 0
        },
        "_api_modes": [
          "getHumidifierStatus",
          "setAutomaticStop",
          "setSwitch",
          "setNightLightBrightness",
          "setVirtualLevel",
          "setTargetHumidity",
          "setHumidityMode",
          "setDisplay",
          "setLevel"
        ]
      }
    ]
  }
}
```

</details>

### Home Assistant log

<details><summary>Logs</summary>

```py
This error originated from a custom integration.

Logger: custom_components.vesync.humidifier
Source: custom_components/vesync/humidifier.py:111
Integration: VeSync
First occurred: 2:40:43 PM (44 occurrences)
Last logged: 3:01:14 PM

Unknown mode 'auto'
```

```py
This error originated from a custom integration.

Logger: custom_components.vesync.humidifier
Source: custom_components/vesync/humidifier.py:133
Integration: VeSync
First occurred: 2:40:43 PM (43 occurrences)
Last logged: 3:01:14 PM

Unknown mode 'auto'
```

```py
This error originated from a custom integration.

Logger: custom_components.vesync.humidifier
Source: custom_components/vesync/humidifier.py:153
Integration: VeSync
First occurred: 2:40:43 PM (306 occurrences)
Last logged: 2:56:44 PM

Unknown mode 'auto'
```

</details>

### Additional information

Setting the humidifier to Manual mode via the Vesync app results in the humidifier entity showing a mode of "Normal".
Selecting "Sleep" mode is reflected correctly.
Auto mode is missing for the humidifier entity.

**Comment by vlebourl** [comment]
Should be fixed in v1.0.0-beta.2. Let me know if it works as expected.

**Comment by RobertD502** [comment]
@vlebourl Unfortunately, it did not. Still missing Auto mode with the same warnings in the logs.

![image](https://user-images.githubusercontent.com/52541649/234305874-2765c6bb-dbfc-47f7-a990-d99be0f105c4.jpeg)

**Comment by vlebourl** [comment]
can you activate debug mode and copy the full log? 
it's strange, that should not be the case...
If I make a custom branch, can you install and try it?

**Comment by RobertD502** [comment]
Logs:

```py

This error originated from a custom integration.

Logger: custom_components.vesync.humidifier
Source: custom_components/vesync/humidifier.py:106 
Integration: VeSync 
First occurred: 10:26:09 AM (2 occurrences) 
Last logged: 10:26:09 AM

Unknown mode 'auto'
```

```py

This error originated from a custom integration.

Logger: custom_components.vesync.humidifier
Source: custom_components/vesync/humidifier.py:128 
Integration: VeSync 
First occurred: 10:26:09 AM (1 occurrences) 
Last logged: 10:26:09 AM

Unknown mode 'auto'
```

```py

This error originated from a custom integration.

Logger: custom_components.vesync.humidifier
Source: custom_components/vesync/humidifier.py:148 
Integration: VeSync 
First occurred: 10:26:09 AM (9 occurrences) 
Last logged: 10:26:09 AM

Unknown mode 'auto'
```

Sure, not a problem!

**Comment by vlebourl** [comment]
damn i messed up with my release ^^'

**Comment by vlebourl** [comment]
Drafted the release before merging the fix... silly me. Try beta.3!

**Comment by RobertD502** [comment]
No worries! Been there myself.
I can confirm that it works now.
